from django.conf import settings


SESSION_REDIS_CLUSTER_HOST = getattr(settings, 'SESSION_REDIS_CLUSTER_HOST', 'localhost')
SESSION_REDIS_CLUSTER_PORT = getattr(settings, 'SESSION_REDIS_CLUSTER_PORT', 6379)
SESSION_REDIS_CLUSTER_DB = getattr(settings, 'SESSION_REDIS_CLUSTER_DB', 0)
SESSION_REDIS_CLUSTER_PREFIX = getattr(settings, 'SESSION_REDIS_CLUSTER_PREFIX', '')
SESSION_REDIS_CLUSTER_PASSWORD = getattr(settings, 'SESSION_REDIS_CLUSTER_PASSWORD', None)

